version: "3.3"

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "9090:9090"
    environment:
      NIFI_WEB_HTTP_PORT: '9090'
    volumes:
        - "<path_to_jdbc>/:/jdbc"

  nifi_2:
    image: apache/nifi:latest
    ports:
      - "9091:9091"
    environment:
      NIFI_WEB_HTTP_PORT: '9091'
    volumes:
        - "<path_to_jdbc>/:/jdbc"

  nifi_registry:
    image: apache/nifi-registry:latest
    ports:
      - "19090:19090"
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: '19090'

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: '192.168.0.205'
      ADVERTISED_PORT: 9092
      TOPICS: 'news'

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    volumes:
        - "<path_to_storage_data>/opt/clickhouse_data:/var/lib/clickhouse"
    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
  # ch_client:
  #     image: yandex/clickhouse-client
  #     command: ['--host', 'server']
  ch_tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - 8080:80

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local